### ISSUE TITLE
Taiwanese is also Chinese!

### ISSUE THREAD

**Issue by caoxu915683474** [Kyubyong/name2nat#1]
Hi, thanks for sharing this good work, however I think there is some mistake in this project. As follow, 
Jing Xu', [('Chinese', 0.8626819252967834), ('Taiwanese', 0.09901007264852524)

Taiwanese is also Chinese! thank you!

**Comment by Kyubyong** [comment]
Hi, I'm going to go into such a political issue in any ways. I just referenced this wiki page: https://en.wikipedia.org/wiki/Lists_of_people_by_nationality. Thanks!!
